[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/subsite/*"
  to = "/subsite/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/subsite/index.html"
  status = 200