[build]
  publish = "dist"
  command = "npm run build"

# Handle redirects for SPA serving from /subsite/
[[redirects]]
  from = "/subsite/*"
  to = "/subsite/index.html"
  status = 200

# Prevent default redirect to SPA - redirect to a placeholder instead
[[redirects]]
  from = "/"
  to = "/root-placeholder.html"
  status = 200

# Prevent any other paths from accessing the SPA except /subsite
[[redirects]]
  from = "/*"
  to = "/root-placeholder.html"
  status = 404